In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("Earthquake.csv")
dataset

time  latitude  longitude  depth  mag magType  \
0      2009-12-31T09:57:29.720Z    27.319     91.510   10.0  5.5      mb   
1      2009-12-29T13:33:22.870Z    35.017     73.005   63.8  4.0      mb   
2      2009-12-29T09:01:55.310Z    24.357     94.807  124.8  5.6     mwb   
3      2009-12-28T02:15:04.870Z    30.686     83.769   10.0  4.4      mb   
4      2009-12-26T00:23:38.570Z    14.001     92.862   42.6  5.0      mb   
...                         ...       ...        ...    ...  ...     ...   
14693  2010-01-11T16:07:13.800Z    36.041     70.893  104.7  4.6      mb   
14694  2010-01-11T05:15:16.160Z    29.744     80.557   35.0  4.7      mb   
14695  2010-01-11T03:38:43.300Z    14.243     93.505   66.4  4.0      mb   
14696  2010-01-05T14:28:18.340Z    32.384     85.273   54.1  4.9      mb   
14697  2010-01-01T02:22:23.820Z    30.646     83.791   10.0  5.2     mwc   

         nst    gap  dmin   rms  ...                   updated  \
0      205.0   37.4   NaN  0.89  ...  2017-04-26T18:09:55.932Z   
1       40.0   95.8   NaN  0.94  ...  2014-11-07T01:40:19.294Z   
2      206.0   17.3   NaN  0.77  ...  2016-11-10T02:22:03.905Z   
3       50.0   40.6   NaN  1.08  ...  2014-11-07T01:40:19.031Z   
4      117.0   68.1   NaN  0.82  ...  2014-11-07T01:40:18.641Z   
...      ...    ...   ...   ...  ...                       ...   
14693   41.0   93.7   NaN  1.11  ...  2014-11-07T01:40:26.476Z   
14694   27.0   84.6   NaN  1.09  ...  2014-11-07T01:40:26.418Z   
14695   18.0  181.4   NaN  0.85  ...  2014-11-07T01:40:26.412Z   
14696   58.0  108.2   NaN  0.83  ...  2014-11-07T01:40:25.340Z   
14697   84.0   78.6   NaN  1.09  ...  2016-11-10T02:22:11.026Z   

                                place        type horizontalError depthError  \
0                              Bhutan  earthquake             NaN        NaN   
1                northwestern Kashmir  earthquake             NaN        8.6   
2         Myanmar-India border region  earthquake             NaN        NaN   
3                      western Xizang  earthquake             NaN        NaN   
4       Andaman Islands, India region  earthquake             NaN        5.7   
...                               ...         ...             ...        ...   
14693  Hindu Kush region, Afghanistan  earthquake             NaN        NaN   
14694       Nepal-India border region  earthquake             NaN        0.0   
14695   Andaman Islands, India region  earthquake             NaN       22.2   
14696                  western Xizang  earthquake             NaN       11.4   
14697                  western Xizang  earthquake             NaN        NaN   

       magError  magNst    status  locationSource magSource  
0           NaN   118.0  reviewed              us        us  
1           NaN     7.0  reviewed              us        us  
2           NaN     NaN  reviewed              us        us  
3           NaN     9.0  reviewed              us        us  
4           NaN    56.0  reviewed              us        us  
...         ...     ...       ...             ...       ...  
14693       NaN     6.0  reviewed              us        us  
14694       NaN     4.0  reviewed              us        us  
14695       NaN     2.0  reviewed              us        us  
14696       NaN    15.0  reviewed              us        us  
14697       NaN     NaN  reviewed              us      gcmt  

[14698 rows x 22 columns]

In [3]:
dataset.columns

Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

In [4]:
dataset.drop(columns=['dmin','net', 'id', 'updated', 'place', 'type',
                      'horizontalError', 'depthError', 'magError', 'magNst', 'status',
                      'locationSource', 'magSource','rms'], axis = 1, inplace=True )
dataset

time  latitude  longitude  depth  mag magType  \
0      2009-12-31T09:57:29.720Z    27.319     91.510   10.0  5.5      mb   
1      2009-12-29T13:33:22.870Z    35.017     73.005   63.8  4.0      mb   
2      2009-12-29T09:01:55.310Z    24.357     94.807  124.8  5.6     mwb   
3      2009-12-28T02:15:04.870Z    30.686     83.769   10.0  4.4      mb   
4      2009-12-26T00:23:38.570Z    14.001     92.862   42.6  5.0      mb   
...                         ...       ...        ...    ...  ...     ...   
14693  2010-01-11T16:07:13.800Z    36.041     70.893  104.7  4.6      mb   
14694  2010-01-11T05:15:16.160Z    29.744     80.557   35.0  4.7      mb   
14695  2010-01-11T03:38:43.300Z    14.243     93.505   66.4  4.0      mb   
14696  2010-01-05T14:28:18.340Z    32.384     85.273   54.1  4.9      mb   
14697  2010-01-01T02:22:23.820Z    30.646     83.791   10.0  5.2     mwc   

         nst    gap  
0      205.0   37.4  
1       40.0   95.8  
2      206.0   17.3  
3       50.0   40.6  
4      117.0   68.1  
...      ...    ...  
14693   41.0   93.7  
14694   27.0   84.6  
14695   18.0  181.4  
14696   58.0  108.2  
14697   84.0   78.6  

[14698 rows x 8 columns]

In [5]:
dataset['time'] = pd.to_datetime(dataset['time'])
dataset['year'] = dataset['time'].dt.year
dataset['month'] = dataset['time'].dt.month_name()
dataset['day'] = dataset['time'].dt.day_name()
dataset['day_of_week'] = dataset['time'].dt.dayofweek
def map_month_to_season(month):
    if month in ['March', 'April', 'May']:
        return 'Spring'
    elif month in ['June', 'July', 'August']:
        return 'Summer'
    elif month in ['September', 'October', 'November']:
        return 'Fall'
    else:
        return 'Winter'
dataset['season'] = dataset['month'].apply(map_month_to_season)
dataset['hour'] = dataset['time'].dt.hour
def hour_to_tod(hour):
    if hour in [4,5,6,7,8,9]:
        return 'Morning'
    elif hour in [10,11,12,13,14,15,16]:
        return 'Noon'
    elif hour in [17,18,19]:
        return 'Evening'
    else:
        return 'Night'
dataset['time_of_day'] = dataset['hour'].apply(hour_to_tod)
dataset.head()


time  latitude  longitude  depth  mag magType  \
0 2009-12-31 09:57:29.720000+00:00    27.319     91.510   10.0  5.5      mb   
1 2009-12-29 13:33:22.870000+00:00    35.017     73.005   63.8  4.0      mb   
2 2009-12-29 09:01:55.310000+00:00    24.357     94.807  124.8  5.6     mwb   
3 2009-12-28 02:15:04.870000+00:00    30.686     83.769   10.0  4.4      mb   
4 2009-12-26 00:23:38.570000+00:00    14.001     92.862   42.6  5.0      mb   

     nst   gap  year     month       day  day_of_week  season  hour  \
0  205.0  37.4  2009  December  Thursday            3  Winter     9   
1   40.0  95.8  2009  December   Tuesday            1  Winter    13   
2  206.0  17.3  2009  December   Tuesday            1  Winter     9   
3   50.0  40.6  2009  December    Monday            0  Winter     2   
4  117.0  68.1  2009  December  Saturday            5  Winter     0   

  time_of_day  
0     Morning  
1        Noon  
2     Morning  
3       Night  
4       Night

In [6]:
dataset = dataset.drop(columns=['time','month','day','hour'])
mag = dataset.pop('mag').values
magType = dataset.pop('magType').values
dataset.insert(9, value=mag, column='mag')
dataset.insert(10, value=magType, column='magType')
dataset.head()

latitude  longitude  depth    nst   gap  year  day_of_week  season  \
0    27.319     91.510   10.0  205.0  37.4  2009            3  Winter   
1    35.017     73.005   63.8   40.0  95.8  2009            1  Winter   
2    24.357     94.807  124.8  206.0  17.3  2009            1  Winter   
3    30.686     83.769   10.0   50.0  40.6  2009            0  Winter   
4    14.001     92.862   42.6  117.0  68.1  2009            5  Winter   

  time_of_day  mag magType  
0     Morning  5.5      mb  
1        Noon  4.0      mb  
2     Morning  5.6     mwb  
3       Night  4.4      mb  
4       Night  5.0      mb

In [7]:
X = dataset.iloc[:,:-2].values
y_mag = dataset.iloc[:,-2].values
y_magType = dataset.iloc[:,-1].values

In [8]:
X

array([[27.319, 91.51, 10.0, ..., 3, 'Winter', 'Morning'],
       [35.017, 73.005, 63.8, ..., 1, 'Winter', 'Noon'],
       [24.357, 94.807, 124.8, ..., 1, 'Winter', 'Morning'],
       ...,
       [14.243, 93.505, 66.4, ..., 0, 'Winter', 'Night'],
       [32.384, 85.273, 54.1, ..., 1, 'Winter', 'Noon'],
       [30.646, 83.791, 10.0, ..., 4, 'Winter', 'Night']], dtype=object)

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[: ,:-2])
X[: , :-2] = imputer.transform(X[: ,:-2])

In [10]:
X

array([[27.319, 91.51, 10.0, ..., 3.0, 'Winter', 'Morning'],
       [35.017, 73.005, 63.8, ..., 1.0, 'Winter', 'Noon'],
       [24.357, 94.807, 124.8, ..., 1.0, 'Winter', 'Morning'],
       ...,
       [14.243, 93.505, 66.4, ..., 0.0, 'Winter', 'Night'],
       [32.384, 85.273, 54.1, ..., 1.0, 'Winter', 'Noon'],
       [30.646, 83.791, 10.0, ..., 4.0, 'Winter', 'Night']], dtype=object)

In [11]:
print(y_mag)
print(y_magType)

[5.5 4.  5.6 ... 4.  4.9 5.2]
['mb' 'mb' 'mwb' ... 'mb' 'mb' 'mwc']


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_mag, test_size=0.25, random_state=0)

In [13]:
X_train

array([[34.712, 73.239, 10.0, ..., 5.0, 'Fall', 'Morning'],
       [19.973, 93.666, 32.2, ..., 1.0, 'Fall', 'Morning'],
       [11.638, 94.353, 30.0, ..., 6.0, 'Winter', 'Evening'],
       ...,
       [36.225, 71.304, 142.3, ..., 3.0, 'Spring', 'Night'],
       [36.4244, 71.3265, 113.13, ..., 3.0, 'Spring', 'Morning'],
       [36.54, 71.467, 229.5, ..., 3.0, 'Winter', 'Noon']], dtype=object)

In [14]:
from sklearn.preprocessing import LabelEncoder
le_train = LabelEncoder()
le_test = LabelEncoder()
X_train[:,-2] = le_train.fit_transform(X_train[:,-2])
X_test[:,-2] = le_test.fit_transform(X_test[:,-2])
X_train[:,-1] = le_train.fit_transform(X_train[:,-1])
X_test[:,-1] = le_test.fit_transform(X_test[:,-1])
X_train

array([[34.712, 73.239, 10.0, ..., 5.0, 0, 1],
       [19.973, 93.666, 32.2, ..., 1.0, 0, 1],
       [11.638, 94.353, 30.0, ..., 6.0, 3, 0],
       ...,
       [36.225, 71.304, 142.3, ..., 3.0, 1, 2],
       [36.4244, 71.3265, 113.13, ..., 3.0, 1, 1],
       [36.54, 71.467, 229.5, ..., 3.0, 3, 3]], dtype=object)

In [15]:
from sklearn.preprocessing import StandardScaler
sc_train= StandardScaler()
sc_test= StandardScaler()
X_train = sc_train.fit_transform(X_train)
X_test = sc_test.fit_transform(X_test)

In [16]:
X_train

array([[ 0.9297584 , -1.12039017, -0.75877798, ...,  0.90582492,
        -1.38793991, -0.80337857],
       [-0.26373435,  0.86253345, -0.378245  , ..., -1.06436215,
        -1.38793991, -0.80337857],
       [-0.93866223,  0.92922305, -0.41595548, ...,  1.39837168,
         1.22672256, -1.79996218],
       ...,
       [ 1.0522738 , -1.3082277 ,  1.5089929 , ..., -0.07926862,
        -0.51638576,  0.19320504],
       [ 1.06842025, -1.30604354,  1.00898627, ..., -0.07926862,
        -0.51638576, -0.80337857],
       [ 1.07778097, -1.29240469,  3.00369903, ..., -0.07926862,
         1.22672256,  1.18978865]])

In [17]:
X_test

array([[-0.32570109,  1.01949772,  0.82938187, ..., -1.06332152,
         1.22302051, -0.79304708],
       [ 0.94265473, -0.37159979, -0.42470164, ..., -0.57528523,
        -1.37201435,  1.22666742],
       [ 0.35880661, -0.87569816, -0.37461924, ..., -0.08724894,
        -0.50700273,  1.22666742],
       ...,
       [ 0.06327607,  0.86386677,  0.0757851 , ..., -1.06332152,
         0.35800889, -0.79304708],
       [-0.0343647 ,  0.90549805,  0.39938148, ..., -0.57528523,
        -0.50700273,  0.21681017],
       [-1.51221867,  0.86445039, -0.42520752, ..., -1.06332152,
         1.22302051,  0.21681017]])

In [18]:
y_train

array([5.6, 5.1, 4.2, ..., 3.8, 4.4, 4.4])

In [19]:
y_test

array([4.9, 4.7, 4.1, ..., 4.2, 3.5, 4.4])

In [20]:
from sklearn.linear_model import LinearRegression
regressor1 =LinearRegression()
regressor1.fit(X_train, y_train)

LinearRegression()

In [21]:
y_pred1 = regressor1.predict(X_test)

In [22]:
y_pred1

array([5.37032964, 4.24609257, 4.23080366, ..., 4.18594283, 4.12589544,
       4.26838945])

In [23]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred1))

0.5869653150939569


In [24]:
from sklearn.model_selection import cross_val_score
accuricies = cross_val_score(estimator= regressor1, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuricies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuricies.std()*100))


Accuracy: 58.09 %
Standard Deviation: 1.86 %


In [25]:
from sklearn.svm import SVR
regressor2 = SVR()
regressor2.fit(X_train, y_train)

SVR()

In [26]:
y_pred2 = regressor2.predict(X_test)
y_pred2

array([5.36370284, 4.22522806, 4.16068619, ..., 4.2603605 , 3.99867198,
       4.35141591])

In [27]:
print(r2_score(y_test, y_pred2))

0.6838100228351336


In [28]:
from sklearn.model_selection import cross_val_score
accuricies = cross_val_score(estimator= regressor2, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuricies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuricies.std()*100))


Accuracy: 68.93 %
Standard Deviation: 1.83 %


In [29]:
X_train = sc_train.inverse_transform(X_train)
X_test = sc_test.inverse_transform(X_test)

In [30]:
from sklearn.ensemble import RandomForestRegressor
regressor3 = RandomForestRegressor(n_estimators=500, random_state=0)
regressor3.fit(X_train,y_train)

RandomForestRegressor(n_estimators=500, random_state=0)

In [31]:
y_pred3 = regressor3.predict(X_test)
y_pred3

array([5.4112, 4.1808, 4.247 , ..., 4.2364, 4.004 , 4.389 ])

In [32]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred3))

0.7217791995383753


In [33]:
from sklearn.model_selection import cross_val_score
accuricies = cross_val_score(estimator= regressor3, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuricies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuricies.std()*100))


Accuracy: 71.63 %
Standard Deviation: 1.89 %
